service: visual-knight-platform

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: dev
  region: eu-central-1
  tracing: true
  profile: serverless-cli-dev-thought

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - '**'

functions:
  webapp:
    handler: apps/backend-webapp/dist/index.handler
    package:
      include:
        - apps/backend-webapp/dist/**
        - apps/backend-webapp/node_modules/**

    events:
      - http:
          method: any
          path: /webapp

  comparison:
    handler: apps/backend-comparison/dist/index.handler
    package:
      include:
        - apps/backend-comparison/dist/**
        - apps/backend-comparison/node_modules/**

    events:
      - http:
          method: any
          path: /comparison
